name: Java CI

on:
  push:
    branches:
      - main
      - phase-1
      - phase-2
      - phase-3
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compile Java files
        run: javac -d out src/*.java

      - name: Run application
        run: java -cp out Main